### ISSUE TITLE
how fast are we talking about?

### ISSUE THREAD

**Issue by master7720** [bush-did-711/eventbus#5]

**Comment by bush-did-711** [comment]
around 2x faster than forge or pomelo, about as fast as Alpine but without the terrible syntax. 

An exact number is irrelevant because the speed depends on what the event listener is actually doing, but my tests were just simple string concatenation and a contains test.

**Comment by M3gaPixel** [comment]
yes !! 2 plus 2 fps ty bush

**Comment by master7720** [comment]
> around 2x faster than forge or pomelo, about as fast as Alpine but without the terrible syntax.
> 
> An exact number is irrelevant because the speed depends on what the event listener is actually doing, but my tests were just simple string concatenation and a contains test.

k thanks for this info
